BlazorIdentity/ViewModels/Account/RedirectViewModel.cs
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

// Original file: https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI
// Modified by Jan Škoruba

namespace BlazorIdentity.ViewModels
{
    public class RedirectViewModel
    {
        public string RedirectUrl { get; set; }
    }
}

BlazorIdentity/Controllers/GrantController.cs
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

// Original file: https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI
// Modified by Jan Škoruba

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Duende.IdentityServer.Events;
using Duende.IdentityServer.Extensions;
using Duende.IdentityServer.Services;
using Duende.IdentityServer.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BlazorIdentity.Helpers;
using BlazorIdentity.ViewModels;
using BlazorIdentity.Users.Constants;
using BlazorIdentityApi.Dtos.Grant;
using BlazorIdentityApi.ExceptionHandling;
using BlazorIdentityApi.Helpers;
using Microsoft.Extensions.Localization;
using BlazorIdentityApi.Services.Interfaces;
using BlazorIdentityApi.Dtos.PersistedGrants;
using BlazorIdentityApi.UI.Api.Mappers;
using Shared;

namespace BlazorIdentity.Controllers
{
    /// <summary>
    /// This sample controller allows a user to revoke grants given to clients
    /// </summary>
    [Authorize(Policy = AuthorizationConsts.AdministrationPolicy)]
    [TypeFilter(typeof(ControllerExceptionFilterAttribute))]
    public class GrantController : BaseController
    {
        private readonly IPersistedGrantAspNetIdentityService _persistedGrantService;
        private readonly IStringLocalizer<GrantController> _localizer;

        public GrantController(IPersistedGrantAspNetIdentityService persistedGrantService,
            ILogger<GrantController> logger,
            IStringLocalizer<GrantController> localizer) : base(logger)
        {
            _persistedGrantService = persistedGrantService;
            _localizer = localizer;
        }

        [HttpGet]
        public async Task<IActionResult> PersistedGrants(int? page, string search)
        {
            ViewBag.Search = search;
            var persistedGrants = await _persistedGrantService.GetPersistedGrantsByUsersAsync(search, page ?? 1);

            return View(persistedGrants);
        }

        [HttpGet]
        public async Task<IActionResult> PersistedGrantDelete(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var grant = await _persistedGrantService.GetPersistedGrantAsync(UrlHelpers.QueryStringUnSafeHash(id));
            if (grant == null) return NotFound();

            return View(grant);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PersistedGrantDelete(PersistedGrantDto grant)
        {
            await _persistedGrantService.DeletePersistedGrantAsync(grant.Key);

            SuccessNotification(_localizer["SuccessPersistedGrantDelete"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(PersistedGrants));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PersistedGrantsDelete(PersistedGrantsDto grants)
        {
            await _persistedGrantService.DeletePersistedGrantsAsync(grants.SubjectId);

            SuccessNotification(_localizer["SuccessPersistedGrantsDelete"], _localizer["SuccessTitle"]);

            return RedirectToAction(nameof(PersistedGrants));
        }


        [HttpGet]
        public async Task<IActionResult> PersistedGrant(string id, int? page)
        {
            var persistedGrants = await _persistedGrantService.GetPersistedGrantsByUserAsync(id, page ?? 1);
            persistedGrants.SubjectId = id;

            return View(persistedGrants);
        }
    }
}

BlazorIdentity/Controllers/KeyController.cs
// Copyright (c) Jan Škoruba. All Rights Reserved.
// Licensed under the Apache License, Version 2.0.

using System.Threading.Tasks;
using BlazorIdentity.Users.Constants;
using BlazorIdentityApi.Dtos.Key;
using BlazorIdentityApi.ExceptionHandling;
using BlazorIdentityApi.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Shared;

namespace BlazorIdentity.Controllers
{
    [Authorize(Policy = AuthorizationConsts.AdministrationPolicy)]
    [TypeFilter(typeof(ControllerExceptionFilterAttribute))]
    public class KeyController : BaseController
    {
        private readonly IKeyService _keyService;
        private readonly IStringLocalizer<KeyController> _localizer;

        public KeyController(IKeyService keyService,
            ILogger<KeyController> logger,
            IStringLocalizer<KeyController> localizer) : base(logger)
        {
            _keyService = keyService;
            _localizer = localizer;
        }

        [HttpGet]
        public async Task<IActionResult> Keys(int? page)
        {
            var keys = await _keyService.GetKeysAsync(page ?? 1);

            return View(keys);
        }

        [HttpGet]
        public async Task<IActionResult> KeyDelete(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var key = await _keyService.GetKeyAsync(id);
            if (key == null) return NotFound();

            return View(key);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> KeyDelete(KeyDto key)
        {
            await _keyService.DeleteKeyAsync(key.Id);

            SuccessNotification(_localizer["Key successfully deleted"], _localizer["Key Deleted"]);

            return RedirectToAction(nameof(Keys));
        }
    }
}

BlazorIdentity/Views/Shared/Redirect.cshtml
@model RedirectViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<h1>@Localizer["Title"]</h1>
<p>@Localizer["SubTitle"]</p>
<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

BlazorIdentity/Views/Shared/_Layout.cshtml
@using BlazorIdentity.Localization
@using BlazorIdentity.Users.Constants
@using Duende.IdentityServer.Extensions
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}

@* @inject SignInManager<ApplicationUser> SignInManager
@{
    var hasExternalLogins = (await SignInManager.GetExternalAuthenticationSchemesAsync()).Any();
} *@
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Duende IdentityServer</title>
    <link rel="icon" type="image/x-icon" href="~/images/skoruba-icon.png" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/skoruba-icon.png" />

    <script src="~/js/knockout-3.5.1.js" asp-append-version="true"></script>
    <script src="~/js/Picker.js" asp-append-version="true"></script>
    <script src="~/js/CryptoUtils.js" asp-append-version="true"></script>
    <script src="~/js/FormMvcHelpers.js" asp-append-version="true"></script>

    <link href="~/dist/css/bundle.min.css" asp-append-version="true" rel="stylesheet" />
    @await Html.PartialAsync("Common/ThemeResources")
    <link href="~/dist/css/web.min.css" asp-append-version="true" rel="stylesheet" />

</head>
<body>

    <div class="menu d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom box-shadow">
        <!--Site name -->

        <h3 class="menu-logo my-0 mr-md-auto font-weight-normal"><a class="logo" asp-area="" asp-controller="Home" asp-action="Index">Duende IdentityServer</a></h3>

        <!--Menu item -->
        @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(name) && (User.IsInRole(role: DefaultRoleNames.Administrator)))
        {
            <!--Menu item -->
            <div class="menu-item my-2 my-md-0 mr-md-3 dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    @Localizer["TitleConfiguration"]
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="Configuration" asp-action="Clients">@Localizer["LinkClients"]</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Configuration" asp-action="IdentityResources">@Localizer["LinkIdentityResources"]</a>
                    <a class="dropdown-item" asp-controller="Configuration" asp-action="ApiResources">@Localizer["LinkApiResources"]</a>
                    <a class="dropdown-item" asp-controller="Configuration" asp-action="ApiScopes">@Localizer["LinkApiScopes"]</a>
                    <a class="dropdown-item" asp-controller="IdentityProvider" asp-action="IdentityProviders">@Localizer["LinkIdentityProviders"]</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Grant" asp-action="PersistedGrants">@Localizer["LinkPersistedGrants"]</a>
                    <a class="dropdown-item" asp-controller="Key" asp-action="Keys">@Localizer["Keys"]</a>
                </div>
            </div>

            <!--Menu item -->
            <div class="menu-item my-2 my-md-0 mr-md-3 dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    @Localizer["TitleUsermanagement"]
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="Identity" asp-action="Users">@Localizer["LinkUsers"]</a>
                    <a class="dropdown-item" asp-controller="Identity" asp-action="Roles">@Localizer["LinkRoles"]</a>
                </div>
            </div>

            <!--Menu item -->
            <div class="menu-item my-2 my-md-0 mr-md-3 dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    @Localizer["Settings"] - @name
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="Manage" asp-action="Index">@Localizer["ManageProfile"]</a>
                    <a class="dropdown-item" asp-controller="Manage" asp-action="PersonalData">@Localizer["ManagePersonalData"]</a>
                    <a class="dropdown-item" asp-controller="Manage" asp-action="TwoFactorAuthentication">@Localizer["2FA"]</a>
                    <a class="dropdown-item" asp-controller="Manage" asp-action="ChangePassword">@Localizer["ChangePassword"]</a>
                    <a class="dropdown-item" asp-controller="Grants" asp-action="Index">@Localizer["Grants"]</a>
                </div>
            </div>

            <a class="menu-item my-2 btn btn-outline-primary" asp-action="Logout" asp-controller="Account">@Localizer["Signout"]</a>

            <!--Menu button - show in < MD -->
            <a class="my-2 btn btn-outline-primary menu-button" href="#">
                <span class="oi oi-menu" title="menu" aria-hidden="true"></span> @Localizer["Menu"]
            </a>
        }

    </div>

    <div class="container">
        @RenderBody()

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-6 col-md">
                    IdentityServer
                    <small class="d-block mb-3 text-muted">@Localizer["FooterCopyright"] @DateTime.Now.Year - v1</small>
                </div>

                <div class="col-md-3 text-right">
                    @await Html.PartialAsync("Common/SelectTheme")
                </div>
                <div class="col-md-3 text-right">
                    @await Html.PartialAsync("Common/SelectLanguage")
                </div>
            </div>
        </footer>
    </div>

    <script src="~/js/bundle.min.js" asp-append-version="true"></script>

    @await Html.PartialAsync("Common/Notification")
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

BlazorIdentity/Views/Shared/_ScopeListItem.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model ScopeViewModel

<li class="list-group-item">
	<div class="toggle-button__input">
		<toggle-button>
			<input class="consent-scopecheck"
				   type="checkbox"
				   name="ScopesConsented"
				   id="scopes_@Model.Value"
				   value="@Model.Value"
				   checked="@Model.Checked"
				   disabled="@Model.Required" />
		</toggle-button>
	</div>
	<div class="toggle-button__text">
		@if (Model.Required)
		{
			<input type="hidden"
				   name="ScopesConsented"
				   value="@Model.Value" />
		}
		<strong>@Model.DisplayName</strong>
		@if (Model.Emphasize)
		{
			<i class="fa fa-exclamation-circle"></i>
		}
	</div>
	@if (Model.Required)
	{
		<div class="toggle-button__text">
			<span><em>@Localizer["Required"]</em></span>
		</div>
	}
	@if (Model.Description != null)
	{
		<div class="consent-description">
			<label for="scopes_@Model.Value">@Model.Description</label>
		</div>
	}
</li>

BlazorIdentity/Views/Shared/_ValidationSummary.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@if (ViewContext.ModelState.IsValid == false)
{
	<div class="alert alert-danger">
		<strong>@Localizer["Title"]</strong>
		<div asp-validation-summary="All" class="danger"></div>
	</div>
}